server:
  port: 8088
spring:
  application:
    name: redis_canal
  # ========================alibaba.druid相关配置=====================
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    druid:
      test-while-ide: false
  # ========================redis相关配置=====================
  redis:
    host: 192.168.122.131
    port: 6379
    password: root

canal:
  destination: example # canal的集群名字，要与安装canal时设置的名称一致
  server: 192.168.122.131:11111 # canal服务地址
# 设置canal消息日志打印级别
logging:
  level:
    org.xiaowu.behappy.canal: debug