server:
  port: 8081
spring:
  application:
    name: dianping
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/redis?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  data:
    redis:
      host: 192.168.122.131
      port: 6379
      password: root
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

oss:
  endpoint: ${OSS_ENDPOINT}
  accessKeyId: ${OSS_ACCESSKEYID}
  accessKeySecret: ${OSS_ACCESSKEYSECRET}
  bucketName: ${OSS_BUCKETNAME}

mybatis-plus:
  type-aliases-package: com.dongguo.dianping.entity # 别名扫描包
logging:
  level:
    com.dongguo.redis: debug
# ========================swagger=====================
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
